"use client";
import { useEffect, useRef, useState } from "react";
import { useVoice } from "./voice-provider";
import { Icon } from "./icon";
import { PushToTalk } from "./ptt-button";
import { ContextPanel, TracePanel } from "./conversation-panels";
import { EmptyState, Modal } from "./ui";

import { SessionTracePanel } from "./session-trace";

export function CallWorkspace() {
  const v = useVoice(); const { t, recorder } = v;

  const [tab, setTab] = useState<"context" | "trace" | "session">("session");
  const [mobileTab, setMobileTab] = useState<"conversation" | "context" | "trace" | "session">("conversation");
  const [replace, setReplace] = useState<(() => void) | null>(null);
  const transcript = useRef<HTMLDivElement>(null); const follow = useRef(true);
  const current = v.session?.turns.find(turn => turn.id === v.selectedTurn) ?? v.session?.turns.at(-1);
  useEffect(() => { if (follow.current && transcript.current) transcript.current.scrollTop = transcript.current.scrollHeight; }, [v.session?.turns]);
  function requestReplace(action: () => void) { if (recorder.phase !== "idle" || v.draft || (v.session?.mode === "live" && !v.session.endedAt)) setReplace(() => action); else action(); }
  function openTrace(id: number) { v.setSelectedTurn(id); setTab("trace"); setMobileTab("trace"); }
  const errorText = (code: string, stage: string) => t(code === "llm_unavailable" ? "modelOffline" : stage === "stt" ? "speechOffline" : stage === "tts" ? "audioOffline" : "turnError");

  return <>
    <div className="page-heading"><div><div className="eyebrow">VOICE ROUTER</div><h1>{t("workspace")}</h1><p>{t("subtitle")}</p></div><div className="heading-actions"><button className="button primary" onClick={() => requestReplace(v.reset)}><Icon name="plus" size={17} />{t("newCall")}</button></div></div>
    <div className="process-strip">{(["step1", "step2", "step3", "step4"] as const).map((key, i) => <div key={key}><span className="process-number">0{i + 1}</span><span>{t(key)}</span>{i < 3 && <Icon name="chevron" size={13} />}</div>)}<span className="process-end"><Icon name="shield" size={15} />Saqta Insurance</span></div>
    <div className="mobile-tabs trace-mobile-tabs segmented"><button aria-pressed={mobileTab === "conversation"} onClick={() => setMobileTab("conversation")}>{t("call")}</button><button aria-pressed={mobileTab === "context"} onClick={() => { setMobileTab("context"); setTab("context"); }}>{t("context")}</button><button aria-pressed={mobileTab === "trace"} onClick={() => { setMobileTab("trace"); setTab("trace"); }}>{t("trace")}</button><button aria-pressed={mobileTab === "session"} onClick={() => { setMobileTab("session"); setTab("session"); }}>{t("callTrace")}</button></div>
    <div className={`workspace-grid mobile-view-${mobileTab}`}><section className="conversation-card"><header className="conversation-header"><div><span className="live-dot" /><strong>{t("call")}</strong>{v.busy && <span className="badge">{t("sending")}</span>}</div><span className={`connection-status ${v.health === "error" ? "connection-error" : ""}`}><span className="tiny-dot" />{t(v.health === "ok" ? "apiOk" : v.health === "error" ? "apiError" : "checking")}</span></header>
      <div className="conversation-scroll" ref={transcript} onScroll={e => { const el = e.currentTarget; follow.current = el.scrollHeight - el.scrollTop - el.clientHeight < 80; }}>
      {v.session?.turns.length ? <div className="transcript">{v.session.turns.map(turn => <div className={`turn-group ${v.selectedTurn === turn.id ? "turn-selected" : ""}`} key={turn.id}><article className="message client-message"><div className="message-meta"><span>{t("client")}</span><span>{turn.language.toUpperCase()} · {t(turn.channel === "voice" ? "voice" : "text")}</span></div><p>{turn.text || t("sending")}</p></article><article className="message assistant-message"><div className="message-meta"><span><span className="assistant-avatar"><Icon name="spark" size={13} /></span>Saqta Voice</span><button className="icon-button" aria-label={t("copy")} disabled={!turn.answer} onClick={() => void v.copy(turn.answer)}><Icon name="copy" size={14} /></button></div><p>{(turn.errors?.some(error => error.message === turn.answer) ? errorText(turn.errors[0].code, turn.errors[0].stage) : turn.answer) || t(turn.status === "processing" ? "sending" : turn.status === "cancelled" ? "stopped" : "unavailable")}</p>{turn.errors?.filter(error => error.message !== turn.answer).map((error, index) => <div className="turn-error" role="status" key={index}><Icon name="info" size={15} /><span>{errorText(error.code, error.stage)}</span></div>)}<button className="turn-route" onClick={() => openTrace(turn.id)}><span>{turn.scenarios[0]?.scenario_id ?? "—"}</span>{t(turn.scenarios.length ? "why" : "trace")}<Icon name="arrow" size={14} /></button></article></div>)}{v.session.outcome === "handoff" && <div className="notice"><Icon name="call" /><p>{t("handoff")}</p></div>}</div> : <div className="welcome"><div className="welcome-orbit"><div className="voice-medallion"><Icon name="mic" size={35} /></div><span className="orbit-dot" /></div><span className="welcome-status"><span className="tiny-dot" />{t("ready")}</span><h2>{t("greeting")}</h2><p>{t("greetingText")}</p><span className="supported-languages"><Icon name="globe" size={15} />{t("supported")}</span></div>}
      </div>
      <div className="composer">{v.capabilities?.mock_mode && <div className="notice"><Icon name="info" size={17} /><p>{t("mockMode")}</p></div>}{v.playback.status === "blocked" && <div className="notice"><p>{t("playbackBlocked")}</p><button className="button secondary" onClick={v.playback.player.resume}>{t("resumeAudio")}</button></div>}{v.playback.status === "playing" && <div className="playback-status" role="status"><Icon name="volume" size={15} />{t("playing")}</div>}
        {(v.notice || recorder.error) && <div className="notice" role="alert"><Icon name="info" size={17} /><p>{t(recorder.error ?? v.notice!)}</p><button className="icon-button" aria-label={t("close")} onClick={() => { v.setNotice(null); if (recorder.error) recorder.discard(); }}><Icon name="close" size={14} /></button></div>}
        {recorder.phase === "ready" && recorder.url && <div className="recording-preview"><div><span className="badge green">{t("recordingReady")}</span><audio controls src={recorder.url} aria-label={t("playback")} /></div><button className="icon-button" aria-label={t("discard")} onClick={recorder.discard}><Icon name="close" /></button><button className="button primary" onClick={() => recorder.blob && void v.send(recorder.blob)} disabled={v.busy}>{t("send")}<Icon name="arrow" size={16} /></button></div>}
        {recorder.phase === "recording" && <div className="recording-indicator"><span className="record-dot" /><strong>{t("recording")}</strong><span className="mono">00:{String(recorder.seconds).padStart(2, "0")}</span><div className="waveform" aria-hidden="true">{Array.from({ length: 24 }, (_, i) => <i key={i} style={{ height: `${4 + recorder.level * (10 + (i % 5) * 7)}px` }} />)}</div><small>max 60 s</small>{v.partial && <p className="live-partial" aria-live="polite">{v.partial}</p>}</div>}
        {v.textOpen && <form className="text-composer" onSubmit={e => { e.preventDefault(); if (v.draft.trim()) void v.send(v.draft.trim()); }}><label className="sr-only" htmlFor="message">{t("write")}</label><textarea id="message" value={v.draft} maxLength={2000} placeholder={t("input")} disabled={v.busy || recorder.phase === "recording"} onChange={e => v.setDraft(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); if (v.draft.trim() && !v.busy && recorder.phase !== "recording") void v.send(v.draft.trim()); } }} /><div><small>{t("inputHint")}</small><button className="button primary" disabled={!v.draft.trim() || v.busy || recorder.phase === "recording"}>{t("send")}<Icon name="arrow" size={15} /></button></div></form>}
        <div className="voice-controls"><div className="voice-controls-primary">{v.busy || v.playback.status === "playing" || v.playback.status === "blocked" ? <button className="button danger" onClick={() => void v.stop()}><Icon name="stop" />{t("stop")}</button> : <><PushToTalk recorder={recorder} disabled={recorder.phase === "ready"} label={t(recorder.phase === "recording" ? "pttRelease" : recorder.phase === "requesting" ? "requesting" : "pttHold")} hint={t("pttHint")} />{recorder.phase === "recording" && <button className="icon-button" onClick={recorder.discard} aria-label={t("cancel")}><Icon name="close" /></button>}</>}<button className={`button quiet ${v.textOpen ? "text-active" : ""}`} aria-pressed={v.textOpen} onClick={() => v.setTextOpen(!v.textOpen)}><Icon name="keyboard" size={19} /><span>{t("write")}</span></button></div>{v.session?.mode === "live" && !v.session.endedAt ? <button className="button quiet" onClick={() => void v.end()}>{t("end")}</button> : <span className="voice-control-hint">RU / KK</span>}</div>
        <div className="composer-footnote"><Icon name="shield" size={12} />{t("synthetic")}<span>·</span><span>Voice Router</span></div>
      </div>
    </section><aside className="insight-panel"><div className="panel-tabs trace-tabs"><button className={tab === "context" ? "active" : ""} aria-pressed={tab === "context"} onClick={() => setTab("context")}><Icon name="layers" size={16} />{t("context")}</button><button className={tab === "trace" ? "active" : ""} aria-pressed={tab === "trace"} onClick={() => setTab("trace")}><Icon name="spark" size={16} />{t("trace")}</button><button className={tab === "session" ? "active" : ""} aria-pressed={tab === "session"} onClick={() => setTab("session")}><Icon name="layers" size={15} />{t("callTrace")}</button></div>{tab === "session" ? <div className="call-session-trace">{v.session?.mode === "live" ? <SessionTracePanel key={v.session.id} sessionId={v.session.id} traceId={v.session.turns.at(-1)?.traceId} live={!v.session.endedAt} compact /> : <EmptyState icon="layers" title={t("traceWaiting")} description={t("traceWaitingText")} />}</div> : tab === "context" ? <ContextPanel session={v.session} /> : <TracePanel session={v.session} turn={current} onSelect={v.setSelectedTurn} />}</aside></div>
    <div className="workspace-footer"><span>HACKALEM AI <span className="footer-slash">/</span> HALYK CHALLENGE</span><span><Icon name="shield" size={13} />{t("explainable")}</span></div>
    {replace && <Modal title={t("newTitle")} onClose={() => setReplace(null)}><p>{t("newText")}</p><div className="dialog-actions"><button className="button secondary" onClick={() => setReplace(null)}>{t("continue")}</button><button className="button primary" onClick={() => { replace(); setReplace(null); }}>{t("newCall")}</button></div></Modal>}
  </>;
}
