"use client";
import { useState } from "react";
import type { Conversation, Fact, Turn } from "@/lib/types";
import { scenarioTitle } from "@/lib/catalog";
import { useVoice } from "./voice-provider";
import { Icon } from "./icon";
import { EmptyState, Modal } from "./ui";

export function FactList({ facts }: { facts: Fact[] }) {
  const { t, copy } = useVoice(); const [source, setSource] = useState<Fact | null>(null);
  return <><div className="facts-list">{facts.map(fact => <article className="fact-card" key={`${fact.key}-${fact.source_id}`}><div className="fact-heading"><Icon name={fact.origin === "background" ? "spark" : "document"} size={16} /><span>{t(fact.origin === "background" ? "fromHelper" : "fromClaim")}</span></div><p>{fact.value}</p><button className="source-link" onClick={() => setSource(fact)}><Icon name="layers" size={13} />{fact.source_id}<Icon name="arrow" size={13} /></button>{fact.usedInTurn && <small className="fact-used"><Icon name="check" size={12} />{t("used")} {fact.usedInTurn}</small>}</article>)}</div>{source && <Modal title={t("source")} onClose={() => setSource(null)}><p className="source-quote">{source.value}</p><dl className="data-list"><div><dt>{t("source")}</dt><dd>{source.source}</dd></div><div><dt>ID</dt><dd>{source.source_id}</dd></div></dl><p className="muted">{t("unavailable")}: raw payload</p><button className="button secondary" onClick={() => void copy(`${source.value}\n${source.source}: ${source.source_id}`)}><Icon name="copy" size={16} />{t("copy")}</button></Modal>}</>;
}
export function ContextPanel({ session }: { session: Conversation | null }) {
  const { t } = useVoice();
  return <div className="context-body"><div className="panel-section-title"><h3>{t("contextTitle")}</h3><Icon name="layers" size={17} /></div>
    {session?.client ? <div className="client-card"><div className="avatar">{session.client.name.split(" ").map(w => w[0]).join("").slice(0, 2)}</div><div><strong>{session.client.name}</strong><p>{session.client.phone}</p><small>{session.client.city}</small></div><Icon name="shield" size={18} /></div> : <div className="identity-empty"><div className="avatar"><Icon name="shield" size={22} /></div><div><strong>{t("noClient")}</strong><p>{t("noClientText")}</p></div></div>}
    {session?.claim && <div className="claim-summary"><div><span>{t("claimExample")}</span><strong className="mono">{session.claim.id}</strong></div><span className="badge amber"><span className="tiny-dot" />{session.claim.status === "documents_requested" ? t("awaitingDocs") : session.claim.status}</span><div className="next-step"><small>{t("nextStep")}</small><p>{session.claim.nextStep}</p></div></div>}
    {session?.facts.length ? <section><h4 className="section-label">{t("facts")}</h4><FactList facts={session.facts} /></section> : <div className="context-placeholder"><div className="placeholder-lines"><span /><span /><span /></div><strong>{t("noFacts")}</strong><p>{t("noFactsText")}</p></div>}
    {session?.confirmation && <section className="confirmation-card"><h4>{t("confirmation")}</h4><strong>{session.confirmation.action}</strong><pre>{JSON.stringify(session.confirmation.params, null, 2)}</pre>{!session.endedAt && <p>{t("confirmationHint")}</p>}</section>}{!!session?.pendingTopics.length && <section><h4 className="section-label">{t("scenarios")}</h4>{session.pendingTopics.map(id => <p key={id}>{id}</p>)}</section>}<div className="helper-card"><div className="helper-heading"><span className="helper-icon"><Icon name="spark" size={18} /></span><strong>{t("assistant")}</strong><span className={`tiny-dot ${session?.helper === "ready" ? "green" : "gray"}`} /></div><p>{session?.helper === "ready" ? t(session.mode === "example" ? "reviewOnly" : "backgroundReady") : t("helperInfo")}</p><span className="helper-state">{session?.helper === "ready" ? t("fromHelper") : session?.helper === "searching" ? t("sending") : session?.helper === "error" ? t("error") : session?.helper === "stale" ? "Результат устарел / Нәтиже ескірген" : t("helperOff")}</span></div>
  </div>;
}
export function TracePanel({ session, turn, onSelect }: { session: Conversation | null; turn?: Turn; onSelect?: (id: number) => void }) {
  const { t, locale, copy } = useVoice(); const [raw, setRaw] = useState(false); const [rawTab, setRawTab] = useState<"response" | "prompt">("response");
  if (!turn) return <EmptyState icon="layers" title={t("noTrace")} description={t("noTraceText")} />;
  return <div className="trace-body"><div className="trace-picker"><label>{t("turn")}<select value={turn.id} onChange={e => onSelect?.(Number(e.target.value))}>{session?.turns.map(item => <option key={item.id} value={item.id}>{item.id} · {item.text.slice(0, 35)}</option>)}</select></label><span className="badge">{turn.language.toUpperCase()}</span></div>
    {session?.mode === "example" && <p className="sample-note">{t("reviewOnly")}</p>}
    {!!turn.errors?.length && <details className="disclosure"><summary>{t("error")}</summary>{turn.errors.map((error, index) => <p key={index}>{error.stage} · {error.code}<br />{error.message}</p>)}</details>}<div className="trace-utterance">“{turn.text}”</div><h4 className="section-label">{t("route")}</h4>
    {!turn.scenarios.length && <p className="muted">{t("noRoute")}</p>}{turn.scenarios.map(route => <article className="route-card" key={route.scenario_id}><div><span className="scenario-id">{route.scenario_id}</span><Icon name="check" size={17} /></div><h3>{scenarioTitle(route.scenario_id, locale)}</h3>{route.reason && <p>{route.reason}</p>}{route.confidence !== undefined && <p className="confidence">{route.confidence.toLocaleString(locale, { maximumFractionDigits: 2 })} · {t("confidence")}</p>}</article>)}
    <details className="disclosure"><summary>{t("alternatives")}<span>{turn.alternatives.length}</span></summary>{turn.alternatives.length ? turn.alternatives.map(a => <p key={a.scenario_id}><span className="mono">{a.scenario_id}</span> {scenarioTitle(a.scenario_id, locale)} {a.confidence}</p>) : <p className="muted">{t("noAlternatives")}</p>}</details>
    <details className="disclosure"><summary>{t("params")}<span>{Object.keys(turn.slots).length}</span></summary><pre>{JSON.stringify(turn.slots, null, 2)}</pre></details>
    {turn.facts.length > 0 && <section><h4 className="section-label">{t("facts")}</h4><FactList facts={turn.facts} /></section>}
    {!!turn.actions?.length && <details className="disclosure"><summary>{t("actions")}<span>{turn.actions.length}</span></summary>{turn.actions.map((action, index) => <div key={index}><p>{action.name} · {action.mode} · {action.ok ? "OK" : t("error")}</p><pre>{JSON.stringify(action.params, null, 2)}</pre></div>)}</details>}<details className="disclosure" open><summary>{t("timings")}<Icon name="clock" size={15} /></summary>{Object.keys(turn.timings).length ? <dl className="data-list">{Object.entries(turn.timings).map(([stage, value]) => <div key={stage}><dt>{stage === "total" ? "Backend total" : stage}</dt><dd>{value} ms</dd></div>)}</dl> : <p className="muted">{t("noTimings")}</p>}</details>
    <p className="muted timing-note">{t("timingNote")}</p><button className="button secondary full-width" onClick={() => setRaw(true)}><Icon name="layers" size={16} />{t("raw")}<Icon name="arrow" size={15} /></button>
    {raw && <Modal title={`${t("raw")} · ${t("turn")} ${turn.id}`} onClose={() => setRaw(false)} wide><div className="segmented"><button aria-pressed={rawTab === "response"} onClick={() => setRawTab("response")}>{t("modelResponse")}</button><button aria-pressed={rawTab === "prompt"} onClick={() => setRawTab("prompt")}>{t("prompt")}</button></div>{session?.mode === "example" && <p className="notice-text">{t("sampleTrace")}</p>}{rawTab === "prompt" ? <p>{turn.prompt ?? t("noPrompt")}</p> : <><pre className="code-block">{JSON.stringify(turn.raw ?? { representation: session?.mode === "example" ? "UI example" : "Received events", scenarios: turn.scenarios, alternatives: turn.alternatives, language: turn.language, slots: turn.slots }, null, 2)}</pre><button className="button secondary" onClick={() => void copy(JSON.stringify(turn.raw ?? turn, null, 2))}><Icon name="copy" size={16} />{t("copy")}</button></>}</Modal>}
  </div>;
}
